name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH command
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            # 1. Navegar a la carpeta donde está tu proyecto en el servidor
            cd /home/deployproindex/proindex
            
            # 2. Descargar los últimos cambios de GitHub
            git pull origin main
            
            # 3. Reiniciar el contenedor de PocketBase para aplicar cambios si fuera necesario
            docker compose down
            docker compose up -d
